// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportingApi1.Data;

#nullable disable

namespace ReportingApi1.Migrations
{
    [DbContext(typeof(VatReportingContext))]
    [Migration("20260413113418_AddUniqueCountryPerVatReport")]
    partial class AddUniqueCountryPerVatReport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReportingApi1.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("ReportingApi1.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            Name = "Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Furniture",
                            Name = "Desk Chair",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Stationery",
                            Name = "Notebook",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            Name = "Monitor",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Furniture",
                            Name = "Standing Desk",
                            Price = 599.99m
                        });
                });

            modelBuilder.Entity("ReportingApi1.Entities.ReportingPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartDate", "EndDate");

                    b.ToTable("ReportingPeriods");
                });

            modelBuilder.Entity("ReportingApi1.Entities.SalesEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("VatReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VatReportId", "Country")
                        .IsUnique();

                    b.ToTable("SalesEntries");
                });

            modelBuilder.Entity("ReportingApi1.Entities.VatReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("ReportingPeriodId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReportingPeriodId");

                    b.HasIndex("CompanyId", "ReportingPeriodId")
                        .IsUnique();

                    b.ToTable("VatReports");
                });

            modelBuilder.Entity("ReportingApi1.Entities.SalesEntry", b =>
                {
                    b.HasOne("ReportingApi1.Entities.VatReport", "VatReport")
                        .WithMany("SalesEntries")
                        .HasForeignKey("VatReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VatReport");
                });

            modelBuilder.Entity("ReportingApi1.Entities.VatReport", b =>
                {
                    b.HasOne("ReportingApi1.Entities.Company", "Company")
                        .WithMany("VatReports")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReportingApi1.Entities.ReportingPeriod", "ReportingPeriod")
                        .WithMany("VatReports")
                        .HasForeignKey("ReportingPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ReportingPeriod");
                });

            modelBuilder.Entity("ReportingApi1.Entities.Company", b =>
                {
                    b.Navigation("VatReports");
                });

            modelBuilder.Entity("ReportingApi1.Entities.ReportingPeriod", b =>
                {
                    b.Navigation("VatReports");
                });

            modelBuilder.Entity("ReportingApi1.Entities.VatReport", b =>
                {
                    b.Navigation("SalesEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
